---

# Installs ElasticHQ front-end. As we already get ES metrics from Prometheus,
# this is *really* optional and should't be necessary anymore

- name: "Ensure Elasticsearch-HQ group exists"
  ansible.builtin.group:
    name: "{{ eshq_group }}"
    system: true

- name: "Ensure Elasticsearch-HQ user exists"
  ansible.builtin.user:
    name: "{{ eshq_user }}"
    home: "{{ eshq_root | dirname }}"
    comment: 'Elasticsearch-HQ dedicated user'
    system: true

- name: "Clone Elasticsearch-HQ from Github"
  become: true
  become_user: "{{ eshq_user }}"
  ansible.builtin.git:
    repo: "{{ eshq_git_repo }}"
    dest: "{{ eshq_root }}"
    version: "{{ eshq_version }}"


- name: "Create python3.6 venv dedicated for Elasticsearch-HQ"
  ansible.builtin.pip:
    requirements: "{{ eshq_root }}/requirements.txt"
    virtualenv: "{{ eshq_venv }}"
    virtualenv_command: /usr/bin/python3 -m venv

- name: "Install Elasticsearch-HQ systemd service unit"
  register: systemd_elastic_hq
  ansible.builtin.template:
    src: elastic/elastic-hq.service.j2
    dest: "/etc/systemd/system/elasticsearch-hq.service"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Reload and activate Elasticsearch-HQ systemd service unit" # noqa no-handler
  when: systemd_elastic_hq.changed
  ansible.builtin.systemd:
    name: elasticsearch-hq
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true

- name: "Configure Apache for ElasticHQ reverse-proxying"
  notify: "Service reload http"
  ansible.builtin.template:
    src: httpd/zz_elastic_hq.conf.j2
    dest: "/etc/httpd/conf.d/15_elastic_hq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
