---
# tasks file for 4any
# vim: bs=2 sw=2 expandtab:

- name: retrieve haproxy IP address
  command: grep -P '^[\d\.]+\s+haproxy$' /etc/hosts
  register: haproxy_out
  failed_when: haproxy_out.rc != 0
  changed_when: haproxy_out.rc != 0

- name: set haproxy IP address fact
  set_fact:
    haproxy_ipaddr: "{{ haproxy_out.stdout | regex_search('^[\\d\\.]+') }}"

- name: ensure xinetd daemon is installed
  yum:
    name: xinetd
    state: latest

- name: set livestatus xinetd configuration
  template:
    src: xinetd_livestatus.j2
    dest: /etc/xinetd.d/livestatus
    owner: root
    group: root
    mode: 0644
  notify: service_restart_xinetd

- name: configure firewalld services
  firewalld:
    port: "{{ xinetd_livestatus_port }}/tcp"
    permanent: yes
    state: enabled

  notify: service_restart_firewalld

- name: ensure xinetd daemon is enabled and running
  systemd:
    name: xinetd
    enabled: yes
    state: started