---
# tasks file for agent_deploy_windows
# vim: bs=2 sw=2 expandtab:
#
# This task-file aims to deploy agents on RGM Windows monitored hosts

- name: check if metricbeat already installed
  win_service:
    name: metricbeat
  register: win_metricbeat_installed

- name: get metricbeat basepath
  set_fact:
    metricbeat_path: "{{ win_metricbeat_installed.path | win_dirname }}"
  when: win_metricbeat_installed.exists

# download and install metricbeat
- block:

  - name: Create temporary build directory
    win_tempfile:
      state: directory
      prefix: rgm-metricbeat
    register: win_tmp

  - name: download windows metricbeat archive
    win_get_url:
      url: "https://{{ rgm_ip_addr }}/distrib/packages/metricbeat-oss-latest-windows-x86_64.zip"
      dest: "{{ win_tmp }}\\metricbeat-oss-latest-windows-x86_64.zip"

  - name: unpack metricbeat archive
    win_unzip:
      src: "{{ win_tmp }}\\metricbeat-oss-latest-windows-x86_64.zip"
      dest: "{{ winbeats_base_path }}"

  - name: find metricbeat directory name
    win_find:
      paths: "{{ winbeats_base_path }}"
      file_type: directory
      patterns: metricbeat-*
    register: find_metricbeat

  - name: get metricbeat basepath
    set_fact:
      metricbeat_path: "{{ find_metricbeat.files[0].path }}"

  - name: install windows service
    win_shell: Powershell -executionpolicy bypass -file "{{ metricbeat_path }}\install-service-metricbeat.ps1"
    notify: win_service_restart_metricbeat

  - name: Set metricbeat startup mode to auto
    win_service:
      name: metricbeat
      start_mode: auto
      notify: win_service_restart_metricbeat

  when: not win_metricbeat_installed.exists

- name: push metricbeat configuration
  template:
    src: distrib/conf/linux_metricbeat.yml.j2
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    group: root
    mode: 0640
  vars:
    client_ip_addr: "{{ ansible_default_ipv4.address }}"
    rgm_ip_addr: "{{ rgm_ip_addr }}"
  notify: win_service_restart_metricbeat