---


{{ rgm_root_path }}

#!/bin/sh

# define path
eondir="/srv/eyesofnetwork"
eonconfdir="/srv/eyesofnetworkconf/cacti"
datadir="${eondir}/cacti"
cactidb="cacti"

# user / group
APPLIANCEGRP="eyesofnetwork"

# cacti datadir
cd ${datadir}

# create the cacti database
mysqladmin -u root --password=root66 create ${cactidb}

# create the database content
mysql -u root --password=root66 ${cactidb} < ${eonconfdir}/cacti-eon.sql

# user / group
touch ${datadir}/log/cacti.log
chown -R cacti:${APPLIANCEGRP} ${datadir}*
chmod -R g+w ${datadir}/log/cacti.log
chmod -R g+w ${datadir}/plugins/weathermap/output/
chmod -R g+w ${datadir}/plugins/weathermap/configs/
rm -rf ${datadir}/plugins/weathermap/configs/.htaccess
/usr/sbin/usermod -g ${APPLIANCEGRP} -G apache cacti

# start the services
/etc/init.d/httpd restart   > /dev/null 2>&1
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                                                                                                                                                                                
~                                                   