---

# This is redundant as all RPM packages are already installed from main tasks
# but we secure it in case the role might be called directly from its tags
- name: ensure Elastic Stack is installed
  yum:
    update_cache: no
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ packages_elastic }}"

### configure metricsbeat

- name: configure metricbeat - reload period
  lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^#?reload.period: '
    line: 'reload.period: 10s'

- name: configure metricbeat - kibana API
  lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^#?host: "localhost:5601"'
    line: "host: \"{{ ansible_default_ipv4.address }}:5601\""

- name: configure metricbeat - elasticsearch output
  lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: '^#?host: "localhost:9200"'
    line: "host: \"{{ ansible_default_ipv4.address }}:9200\""
