---

- name: include ES common preliminary tasks
  include_tasks:
    file: elastic_common_pre.yml

- name: configure elasticsearch for cluster mode
  template:
    src: elastic/elasticsearch-cluster.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0644
  notify: service_restart_elasticsearch
  register: elasticsearch_conf

- name: configure firwalld trusted zone
  firewalld:
    zone: trusted
    source: "{{ hostvars[item].ansible_default_ipv4.address }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: "{{ groups['rgm'] }}"

- name: configure firwalld for elastic cluster mode
  firewalld:
    zone: trusted
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - '9200/tcp'
    - '9300/tcp'

- name: include ES common post tasks
  include_tasks:
    file: elastic_common_post.yml

- name: check Apache HTTPd server configured for RGM
  stat:
    path: /etc/httpd/conf.d/rgmweb.conf
  register: stat_httpd_rgm

- include_tasks:
    file: elastic_hq.yml
  when: stat_httpd_rgm.stat.exists

