---
# Tasks for Elastic Stack RGM setup
# vim: bs=2 sw=2 expandtab:

# This is redundant as all RPM packages are already installed from main tasks
# but we secure it in case the role might be called directly from its tags
- name: ensure Elastic Stack is installed
  yum:
    update_cache: no
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ packages_elastic }}"
  tags:
  - elastic
  - kibana
  - metricbeat


 ### Configure Elasticsearch

- name: create elastic backup repo directory
  file:
    path: /srv/rgm/elastic
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
    state: directory
  
- name: configure Elasticsearch config file
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
  - { regex: '^(#\s*)?network.host: ',  line: "network.host: ['127.0.0.1']" }
  - { regex: '^(#\s*)?path.repo: ',     line: 'path.repo: "/srv/rgm/elastic"' }
  notify: service_restart_elasticsearch
  tags: elastic

- name: create an elasticsearch local backup reposotory
#curl -XPUT 'http://127.0.0.1:9200/_snapshot/backup' -H 'Content-Type: application/json' -d '{ "type": "fs", "settings": {"location": "/srv/rgm/elastic/backups","compress": true}}'

# backup kibana:
  # curator_cli  snapshot --repository backup --name ".kibana_empty" --filter_list '{"filtertype": "pattern", "kind": "prefix", "value": ".kibana", "exclude": "False"}'


- name: copy curator config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - { src: 'elastic/curator_actions.yml.j2',    dst: '/etc/elasticsearch/actions.yml' }
  - { src: 'elastic/curator.yml.j2',            dst: '/etc/elasticsearch/curator.yml' }
  tags: elastic

- name: set cron job for curator
  copy:
    content: "10 0 * * * * root /usr/bin/curator --config /etc/elasticsearch/curator.yml /etc/elasticsearch/actions.yml &> /dev/null"
    dest: /etc/cron.d/elastic_curator
    owner: root
    group: root
    mode: 0644
  tags: elastic


### Configure kibana

- name: configure Kibana config file
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
  - { regex: '^(#\s*)?server.port',              line: 'server.port: 5601' }
  - { regex: '^(#\s*)?server.host',              line: 'server.host: "localhost"' }
  - { regex: '^(#\s*)?server.basePath',          line: 'server.basePath: "/kibana"' }
  - { regex: '^(#\s*)?server.rewriteBasePath',   line: 'server.rewriteBasePath: true' }
  tags: kibana


### configure metricsbeat

- name: configure metricbeat - reload period
  lineinfile:
    path: /etc/metricbeat/metricbeat.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
  - { regex: '^(#\s*)?reload.period: ',     line: 'reload.period: 10s' }
  - { regex: '^(#\s*)?host:\s+".*:5601"',   line: "host: \"127.0.0.1:5601\""}
  - { regex: '^(#\s*)?host:\s+".*:9200"',   line: "host: \"127.0.0.1:9200\"" }
  tags: metricbeat

