---

- name: include ES common preliminary tasks
  include_tasks:
    file: elastic_common_pre.yml

- name: configure Elasticsearch config file
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  with_items:
  - { regex: '^(#\s*)?network.host: ',  line: "network.host: ['127.0.0.1']" }
  - { regex: '^(#\s*)?path.repo: ',     line: 'path.repo: "/srv/rgm/elastic"' }
  notify: service_restart_elasticsearch
  register: elasticsearch_conf

- name: include ES common post tasks
  include_tasks:
    file: elastic_common_post.yml



#- name: create an elasticsearch local backup reposotory
#curl -XPUT 'http://127.0.0.1:9200/_snapshot/backup' -H 'Content-Type: application/json' -d '{ "type": "fs", "settings": {"location": "/srv/rgm/elastic/backups","compress": true}}'

# backup kibana:
  # curator_cli  snapshot --repository backup --name ".kibana_empty" --filter_list '{"filtertype": "pattern", "kind": "prefix", "value": ".kibana", "exclude": "False"}'



# curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'