---

- name: ensure Elasticsearch-HQ group exists
  group:
    name: "{{ eshq_group }}"
    system: yes

- name: ensure Elasticsearch-HQ user exists
  user:
    name: "{{ eshq_user }}"
    home: "{{ eshq_root | dirname }}"
    comment: 'Elasticsearch-HQ dedicated user'
    system: yes

- name: clone Elasticsearch-HQ from Github
  git:
    repo: "{{ eshq_git_repo }}"
    dest: "{{ eshq_root }}"
    version: "{{ eshq_version }}"
  become: yes
  become_user: "{{ eshq_user }}"

- name: create python3.6 venv dedicated for Elasticsearch-HQ
  pip:
    requirements: "{{ eshq_root }}/requirements.txt"
    virtualenv: "{{ eshq_venv }}"
    virtualenv_command: /usr/bin/python3 -m venv

- name: install Elasticsearch-HQ systemd service unit
  template:
    src: elastic/elastic-hq.service.j2
    dest: /etc/systemd/system/elasticsearch-hq.service
    owner: root
    group: root
    mode: 0644
  register: systemd_elastic_hq

- name: reload and activate Elasticsearch-HQ systemd service unit
  systemd:
    name: elasticsearch-hq
    state: restarted
    enabled: true
    masked: false
    daemon_reload: true
  when: systemd_elastic_hq.changed

- name: configure Apache for ElasticHQ reverse-proxying
  template:
    src: httpd/15_elastic_hq.conf.j2
    dest: /etc/httpd/conf.d/15_elastic_hq.conf
    owner: root
    group: root
    mode: 0644
  notify: service_reload_http