---
# Tasks for Grafana/Histou RGM setup
# vim: bs=2 sw=2 expandtab:

# This is redundant as all RPM packages are already installed from main tasks
# but we secure it in case the role might be called directly from its tags
- name: ensure Grafana & Co packages are present
  yum:
    update_cache: no
    name: "{{ packages }}"
    state: present
  vars:
    packages: "{{ packages_influx_grafana }}"
  tags: grafana

- name: creates Grafana RGM dashboards directory
  file:
    path: "{{ grafana_rgm_dashboards }}"
    owner: grafana
    group: "{{ rgm_group }}"
    mode: 0755
    state: directory

- name: copy grafana patches
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - { owner: 'root',    group: 'root', mode: '0644', src: grafana/grafana_icon.svg,          dest: /usr/share/grafana/public/img/grafana_icon.svg }
  - { owner: 'root',    group: 'root', mode: '0744', src: grafana/grafana_rgm.sh,            dest: /etc/grafana/grafana_rgm.sh }
  - { owner: 'grafana', group: 'rgm',  mode: '0644', src: grafana/system-metrics.json,       dest: "{{ grafana_rgm_dashboards }}/system-metrics.json" }
  - { owner: 'grafana', group: 'rgm',  mode: '0644', src: grafana/multi-system-metrics.json, dest: "{{ grafana_rgm_dashboards }}/multi-system-metrics.json" }
  tags: grafana

- name: apply patches to align Grafana theme on RGM theme
  script: /etc/grafana/grafana_rgm.sh
  args:
    executable: /bin/bash
  register: grafana_patch
  failed_when: grafana_patch.rc == 255
  changed_when: grafana_patch.rc > 0
  tags: grafana
  
- name: "configure grafana.ini file"
  ini_file:
    path: /etc/grafana/grafana.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'paths',             option: 'logs',                 value: '/var/log/grafana' }
  - { section: 'paths',             option: 'plugins',              value: '/var/lib/grafana/plugins' }
  - { section: 'server',            option: 'protocol',             value: 'http' }
  - { section: 'server',            option: 'http_addr',            value: "{{ grafana_http_addr }}" }
  - { section: 'server',            option: 'http_port',            value: "{{ grafana_http_port }}" }
  - { section: 'server',            option: 'domain',               value: "{{ grafana_domain }}" }
  - { section: 'server',            option: 'root_url',             value: "http://{{ grafana_domain }}{{ grafana_root_url }}/" }
  - { section: 'analytics',         option: 'reporting_enabled',    value: 'false' }
  - { section: 'analytics',         option: 'check_for_updates',    value: 'false' }
  - { section: 'database',          option: 'type',                 value: 'mysql' }
  - { section: 'database',          option: 'host',                 value: '127.0.0.1:3306' }
  - { section: 'database',          option: 'name',                 value: "{{ db_grafana }}" }
  - { section: 'database',          option: 'user',                 value: "{{ mariadb_user }}" }
  - { section: 'database',          option: 'password',             value: "{{ mariadb_pwd }}" }
  - { section: 'security',          option: 'admin_user',           value: 'admin' }
  - { section: 'users',             option: 'default_theme',        value: 'light' }
  - { section: 'auth',              option: 'disable_login_form',   value: 'true' }
  - { section: 'auth',              option: 'disable_signout_menu', value: 'true' }
  - { section: 'auth.anonymous',    option: 'enabled',              value: 'false' }
  - { section: 'auth.anonymous',    option: 'org_role',             value: 'Viewer' }
  - { section: 'auth.github',       option: 'enabled',              value: 'false' }
  - { section: 'auth.google',       option: 'enabled',              value: 'false' }
  - { section: 'auth.generic_oauth',option: 'enabled',              value: 'false' }
  - { section: 'auth.grafana_com',  option: 'enabled',              value: 'false' }
  - { section: 'auth.proxy',        option: 'enabled',              value: 'true' }
  - { section: 'auth.proxy',        option: 'header_name',          value: 'X-WEBAUTH-USER' }
  - { section: 'auth.proxy',        option: 'header_property',      value: 'username' }
  - { section: 'auth.proxy',        option: 'auto_sign_up',         value: 'false' }
  - { section: 'auth.basic',        option: 'enabled',              value: 'false' }
  - { section: 'auth.ldap',         option: 'enabled',              value: 'false' }
  notify: service_restart_grafana
  register: grafana_ini_changed
  tags: grafana

- name: "create histoujs symlink on Grafana public dir"
  file:
    path: /usr/share/grafana/public/dashboards/histou.js
    src: /srv/rgm/histou/histou.js
    state: link
    mode: 0644
  tags: grafana

- name: set grafana datasources and dashboards
  template:
    src: "grafana/{{ item.src }}"
    dest: "/etc/grafana/provisioning/{{ item.dest }}"
    owner: root
    group: grafana
    mode: 0640
  with_items:
  - { src: rgm_ds.yml.j2,   dest: datasources/rgm_ds.yaml }
  - { src: rgm_dash.yml.j2, dest: dashboards/rgm_dash.yaml }
  tags: grafana

- name: install grafana plugins
  grafana_plugin:
    name: "{{ item }}"
    state: present
  with_items: "{{ grafana_plugins }}"
  when: grafana_install_plugins
  notify: service_restart_grafana
  tags: grafana
