---

## add apache user to rgm group

- name: "add {{ rgm_group }} to apache user"
  user:
    name: apache
    groups: " {{ rgm_group }}"
    append: yes

## php configuration

- shell: ls -l /etc/localtime |awk -F "zoneinfo/" '{print $2}'
  args:
    executable: /bin/bash
  register: local_tz

#- name: set local time zone fact
#  set_fact:
#    localtime: local_tz.stdout

- name: set Europe/Paris TZ for php
  lineinfile:
    path: /etc/php.ini
    regexp: '^;*\s*date.timezone *=.*'
    line: "date.timezone = Europe/Paris"
  notify: service_reload_http

- name: set memory limit for php
  lineinfile:
    path: /etc/php.ini
    regexp: '^;*\s*memory_limit *=.*'
    line: "memory_limit = 256M"
  notify: service_reload_http

- name: set max_execution_time for php
  lineinfile:
    path: /etc/php.ini
    regexp: '^;*\s*max_execution_time *=.*'
    line: "max_execution_time = 300"
  notify: service_reload_http

- name: set error_reporting for php
  lineinfile:
    path: /etc/php.ini
    regexp: '^;*\s*error_reporting *=.*'
    line: "error_reporting = E_ERROR"
  notify: service_reload_http

## apache configuration

- name: set Apache root path
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot'
    line: "DocumentRoot \"{{ rgm_root_path }}/rgmweb\""
  notify: service_reload_http

