---
# tasks for Apache/php RGM setup
# vim: bs=2 sw=2 expandtab:

# This is redundant as all RPM packages are already installed from main tasks
# but we secure it in case the role might be called directly from its tags
- name: ensure Apache/php is installed
  yum:
    update_cache: no
    name: "{{ packages_apache }}"
    state: present

## add apache user to rgm group

- name: "add {{ rgm_group }} to apache user"
  user:
    name: apache
    groups: " {{ rgm_group }}"
    append: yes

## php configuration

- name: "configure php.ini file"
  ini_file:
    path: /etc/php.ini
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - { section: 'Date', option: 'date.timezone',      value: 'Europe/Paris' }
  - { section: 'PHP',  option: 'memory_limit',       value: '256M' }
  - { section: 'PHP',  option: 'max_execution_time', value: '300' }
  - { section: 'PHP',  option: 'error_reporting',    value: 'E_ERROR' }
  - { section: 'PHP',  option: 'expose_php',         value: 'Off' }
  notify: service_reload_http

## apache configuration

- name: set Apache root path
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot'
    line: "DocumentRoot \"{{ rgm_root_path }}/rgmweb\""
  notify: service_reload_http

- name: backup ssl.conf original (distrib) file
  copy:
    remote_src: yes
    force: no
    src: /etc/httpd/conf.d/ssl.conf
    dest: /etc/httpd/conf.d/ssl.conf.distrib

- name: Install RGM httpd config files
  template:
    src: "httpd/{{ item }}.conf.j2"
    dest: "/etc/httpd/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: 0644
  with_items:
  - 00_hardening
  - 01_ssl
  - 10_rgm
  - 11_rgmapi
  - 11_distrib
  - 15_grafana
  - 15_elasticsearch
  - 15_kibana
  - 15_nrdp
  - 15_rgma
  notify: service_reload_http

## restart apache now as we'll use RGM API later on role
- name: flush handlers
  meta: flush_handlers
