---
# tasks file for ansible-role-rgm

# As nagios 4 is present in EPEL repo, disable nagios from EPEL
- name: "exclude nagios from {{ item }}"
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: "{{ item }}"
    option: exclude
    value: 'nagios*'
  with_items:
  - epel
  - epel-debuginfo
  - epel-source
  register: update_epel

- name: force yum clean & make cache
  yum:
    update_cache: yes
  when: update_epel

### selinux
# todo: configure RGM to work smoothly *with* selinux enabled
- name: disable SELinux
  selinux:
    state: disabled

### MariaDB base configuration
- name: configure mariadb
  include_tasks: mariadb.yml
  tags:
  - mariadb

### installs RGM packages & dependencies
- name: install RGM packages (it may take some time...)
  yum:
    update_cache: no
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - bash-completion
    - vim
    - sudo
    - net-snmp
    - snmptt
    - chrony
    - influxdb
    - grafana
    - httpd
    - mod_auth_rgm
    - mod_perl
    - mod_ssl
    - mod_fcgid
    - php
    - php-mysqlnd
    - php-ldap
    - php-process
    - php-xml
    - php-snmp
    - mk-livestatus
    - nagflux
    - histou
    - nagios
    - nagios-plugins
    - nagvis
    - nagiosbp
    - notifier
    - ged
    - ged-mysql
    - thruk
    - lilac
    - rgmweb

  retries: 10
  delay: 2
  register: yum_result
  until: yum_result.rc == 0

### sudoers base configuration
- name: set sudoers config file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/rgm"
    owner: root
    group: root
    mode: 0400
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

### configure chronyd
- name: configure chrony daemon
  include_tasks: ntp.yml
  tags:
  - ntp
  - chrony


### php base configuration
- name: configure apache/php
  include_tasks: http.yml
  tags:
  - httpd
  - php


### configure elastic/influxdb
- name: configure elastic stack
  include_tasks: elastic.yml
  tags:
  - elastic
  - metricbeat

- name: configure influxdb
  include_tasks: influx.yml
  tags:
  - influxdb
  - nagflux
  - histou
  - grafana

- name: kernel hardening (sysctl)
  copy:
    src: sysctl_ansii.conf
    dest: /etc/sysctl.d/ansii-fr.conf
    owner: root
    group: root
    mode: 0644

### firewalld configuration
- name: configure firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - ssh
  - http
  - https


### enable and start RGM services
- name: enable RGM daemons
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ rgm_services }}"
