---
# tasks file for ansible-role-rgm

- name: install package dependencies (please be patient, it may take some time...)
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - sudo
    - net-snmp
    - mariadb-server
    - httpd
    - mod_auth_rgm
    - mod_perl
    - php
    - php-mysql
    - php-ldap
    - php-process
    - php-xml
    - nagios
    - nagvis
    - nagiosbp
    - notifier
    - ged
    - ged-mysql
    - thruk
    - lilac
    - rgmweb


### selinux
# todo: configure RGM to work smoothly *with* selinux enabled
- name: disable SELinux
  selinux:
    state: disabled


###### system users & groups base configuration
###- name: "create RGM '{{ rgm_group }}' group"
###  group:
###    name: "{{ rgm_group }}"
###    state: present
###
###- name: "add {{ rgm_group }} to apache user"
###  user:
###    name: apache
###    groups: " {{ rgm_group }}"
###    append: yes
# commented out as this should be done by packaging system


### sudoers base configuration
- name: set sudoers config file
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/rgm"
    owner: root
    group: root
    mode: 0400
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

# todo: config chronyd

### MariaDB base configuration
- name: configure mariadb
  include_tasks: mariadb.yml
  tags:
  - mariadb


### php base configuration
- name: configure apache/php
  include_tasks: http.yml
  tags:
  - httpd
  - php


### firewalld configuration
- name: configure firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
  - ssh
  - http
  - https

### enable and start RGM services
- name: enable RGM daemons
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items: "{{ rgm_services }}"
