---
# tasks for mariadb_db RGM setup
# mariadb database creation
# vim: bs=2 sw=2 expandtab:


- name: "ensure {{ db_name }} database exists"
  mysql_db:
    name: "{{ db_name }}"
    state: present
  register: mysql_db_created

- name: "grant {{ db_user }} user to {{ db_name }} database"
  mysql_user:
    host: localhost
    name: "{{ db_user }}"
    password: "{{ db_pwd }}"
    priv: "{{ db_name }}.*:ALL"
    append_privs: yes
    login_user: root
    state: present
  when: mysql_db_created.changed