---
- name: generate random backup password for mariadb
  set_fact:
    mariadb_backup_password: "{{ lookup('password', '/dev/null length=48 chars=ascii_letters,digits,-,_,!,.,*') }}"
  no_log: True

- name: "create and grant {{ mariadb_backup_username }} user to backup database"
  mysql_user:
    host: localhost
    name: "{{ mariadb_backup_username }}"
    password: "{{ mariadb_backup_password }}"
    priv: '*.*:SELECT,LOCK TABLES,USAGE'
    login_user: root
    state: present

- name: set .my-backup.cnf for backup user
  template:
    src: mariadb/my.cnf.j2
    dest: /root/.my-backup.cnf
    owner: root
    group: root
    mode: 0600
  vars:
    mariadbuser: '{{ mariadb_backup_username }}'
    mariadbpasswd: "{{ mariadb_backup_password }}"
  no_log: True