---
- name: "Elastic | Ensure ElasticStack is installed"
  tags:
    - packages
  ansible.builtin.yum:
    update_cache: false
    name: "{{ packages.elastic }}"
    state: present

- name: "Elastic | Ensure ElasticStack curator is installed on EL7"
  when:
    - ansible_distribution_major_version|int == 7
  tags:
    - packages
  ansible.builtin.yum:
    update_cache: false
    name: "{{ packages.elasic_el7 }}"
    state: present

- name: "Elastic | Install elastic curator from pip on EL9"
  when:
    - ansible_distribution_major_version|int >= 9
  block:
    - name: "Elasticsearch | Create venv for curator on EL9"
      ansible.builtin.pip:
        virtualenv: "{{ curator.venv_path }}"
        virtualenv_command: /usr/bin/python3 -m venv
        extra_args: '--upgrade'
        name:
          - pip
          - setuptools
    - name: "Elasticsearch | Install curator on EL9"
      ansible.builtin.pip:
        virtualenv: "{{ curator.venv_path }}"
        name:
          - elasticsearch==7.12.0
          - elasticsearch-curator==5.8.4

    - name: "Elasticsearch | Create symlink to system binary path"
      ansible.builtin.file:
        src: /opt/elasticsearch-curator/bin/curator
        path: /usr/bin/curator
        owner: 'root'
        group: 'root'
        state: link

- name: "Elastic | Clean elasticsearch sto"
  when:
    - force_delete_es is defined
    - force_delete_es
  block:
    - name: "Elastic | Ensure elasticsearch is stopped"
      ansible.builtin.systemd:
        name: elasticsearch
        state: stopped

    - name: "Elastic | Force ES sto deletion"
      ansible.builtin.file:
        path: "/var/lib/elasticsearch/nodes"
        state: absent

- name: "Elastic | Create elastic backup repo directory"
  ansible.builtin.file:
    path: "/srv/rgm/elastic"
    owner: "elasticsearch"
    group: "{{ rgm_group }}"
    mode: "0750"
    state: directory
    recurse: true

- name: "Elastic | Import elasticsearch postinstall tasks"
  ansible.builtin.import_tasks: elastic/elastic_postinstall.yml

- name: "Elastic | Import elasticsearch configuration tasks"
  ansible.builtin.import_tasks: elastic/elastic_configure.yml

- name: "Elastic | Import elastic postdeploy tasks"
  ansible.builtin.import_tasks: elastic/elastic_postdeploy.yml

- name: "Elastic | Ensure elasticsearch is enabled and started"
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started

- name: "Elastic | Import elasticsearch curator tasks"
  ansible.builtin.import_tasks: elastic/elastic_curator.yml
