---
# handlers file for role-rgm
# vim: bs=2 sw=2 expandtab:

- name: service_restart_mariadb
  service:
    name: mariadb
    state: restarted

- name: service_reload_http
  service:
    name: httpd
    state: reloaded

- name: service_restart_firewalld
  service:
    name: firewalld
    state: restarted

- name: service_reload_nagios
  service:
    name: nagios
    state: reloaded

- name: service_reload_ged
  service:
    name: gedd
    state: reloaded

- name: service_restart_chrony
  service:
    name: chronyd
    state: restarted

- name: service_reload_crond
  service:
    name: crond
    state: reloaded

- name: service_restart_elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: service_restart_kibana
  service:
    name: kibana
    state: restarted

- name: service_restart_metricbeat
  service:
    name: metricbeat
    state: restarted

- name: service_restart_filebeat
  service:
    name: filebeat
    state: "{{ filebeat_enabled | ternary('restarted', 'stopped') }}"

- name: service_restart_influxdb
  service:
    name: influxdb
    state: restarted

- name: service_restart_nagflux
  service:
    name: nagflux
    state: restarted

- name: service_restart_grafana
  service:
    name: grafana-server
    state: restarted

- name: service_restart_prometheus
  service:
    name: prometheus
    state: restarted

- name: service_restart_influxdb_exporter
  service:
    name: influxdb_exporter
    state: restarted

- name: service_restart_xinetd
  service:
    name: xinetd
    state: restarted

- name: win_service_restart_metricbeat
  win_service:
    name: metricbeat
    state: restarted

- name: insert SQL procedures on rgmweb DB
  shell: mysql rgmweb < /var/lib/rgm/rgmweb/sql/one-liners.sql
  args:
    executable: /bin/bash
  register: oneliner_sql_exec
  changed_when: oneliner_sql_exec.rc == 1
  failed_when: oneliner_sql_exec.rc == 2