---
# handlers file for ansible-role-rgm
# vim: bs=2 sw=2 expandtab:

- name: service_restart_mariadb
  service:
    name: mariadb
    state: restarted

- name: service_reload_http
  service:
    name: httpd
    state: reloaded

- name: service_restart_firewalld
  service:
    name: firewalld
    state: restarted

- name: service_reload_nagios
  service:
    name: nagios
    state: reloaded

- name: service_reload_ged
  service:
    name: gedd
    state: reloaded

- name: service_restart_chrony
  service:
    name: chronyd
    state: restarted

- name: service_restart_elasticsearch
  service:
    name: elasticsearch
    state: restarted

- name: service_restart_metricbeat
  service:
    name: metricbeat
    state: restarted

- name: service_restart_influxdb
  service:
    name: influxdb
    state: restarted

- name: service_restart_nagflux
  service:
    name: nagflux
    state: restarted

- name: service_restart_grafana
  service:
    name: grafana-server
    state: restarted
