---
- name: "Business | BED | Start bed-ping" # noqa no-handler
  ansible.builtin.systemd:
    name: bed-ping
    state: started
    masked: false
    daemon_reload: true

- name: "Business | BED | Ensure bed can contact SCC infra"
  register: heavendoor_status
  ansible.builtin.uri:
    url: '{{ bed.stargate_scc.health_url }}'

- name: "Business | BED | Ensure bed-ping is started" # noqa no-handler
  when: heavendoor_status.status == '200'
  loop:
    - bed-ping
    - bed-runner
    - bed-metro
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    masked: false
    daemon_reload: true