---
- name: "Prerequisites | Hardening | Kernel hardening (sysctl) following ANSII recomendations"
  register: sysctl_ansii
  ansible.builtin.copy:
    src: sysctl_ansii.conf
    dest: "/etc/sysctl.d/ansii-fr.conf"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Prerequisites | Hardening | Reload sysctl" # noqa no-handler
  when: sysctl_ansii.changed
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted

- name: "Prerequisites | Hardening | Set swappiness (sysctl)"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ sysctl_swappiness | string }}"
    state: present
    sysctl_file: "/etc/sysctl.d/98-swappiness.conf"
    reload: true

- name: "Prerequisites | Hardening | SSH Hardening"
  tags:
    - ssh_hardening
  when: ssh_hardening
  block:
    - name: "Prerequisites | Hardening | Disable weak SSH ECDSA host keys"
      loop:
        - { file: ssh_host_ecdsa_key,     mode: '0400' } # noqa yaml[commas]
        - { file: ssh_host_ecdsa_key.pub, mode: '0644' } # noqa yaml[commas]
      notify: "Service restart sshd"
      ansible.builtin.copy:
        content: ''
        dest: "/etc/ssh/{{ item.file }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"

    - name: "Prerequisites | Hardening | SSH daemon hardening base"
      loop:
        - { regex: '^(#\s*)?SyslogFacility',               line: "SyslogFacility AUTHPRIV" }  # noqa yaml[commas]
        - { regex: '^(#\s*)?PermitEmptyPasswords',         line: "PermitEmptyPasswords no" } # noqa yaml[commas]
        - { regex: '^(#\s*)?PermitRootLogin',              line: "PermitRootLogin without-password" } # noqa yaml[commas]
        - { regex: '^(#\s*)?StrictModes',                  line: "StrictModes yes" } # noqa yaml[commas]
        - { regex: '^HostKey /etc/ssh/ssh_host_ecdsa_key', line: "#HostKey /etc/ssh/ssh_host_ecdsa_key" } # noqa yaml[commas]
        - { regex: '^(#\s*)?RekeyLimit ',                  line: "RekeyLimit default 1200" } # noqa yaml[commas]
        - { regex: '^(#\s*)?TCPKeepAlive ',                line: "TCPKeepAlive yes" } # noqa yaml[commas]
        - { regex: '^(#\s*)?MaxSessions ',                 line: "MaxSessions 10" } # noqa yaml[commas]
      notify: "Service restart sshd"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        insertafter: '^(#\s*)?UsePAM '

    - name: "Prerequisites | Hardening | SSH daemon hardening for EL7"
      when:
        ansible_distribution_major_version|int == 7
      loop:
        - { regex: '^(#\s*)?Ciphers ',                     line: "Ciphers aes128-ctr,aes192-ctr,aes256-ctr" } # noqa yaml[commas]
        - { regex: '^(#\s*)?MACs ',                        line: "MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160" } # noqa yaml[commas]
        - { regex: '^(#\s*)?KexAlgorithms ',               line: "KexAlgorithms diffie-hellman-group-exchange-sha256" } # noqa yaml[commas]
      notify: "Service restart sshd"
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: "{{ item.regex }}"
        line: "{{ item.line }}"
        insertafter: '^(#\s*)?UsePAM '

    - name: "SSH Hardening for RHEL 9"
      when:
        - ansible_distribution_major_version|int == 9
      block:
        - name: "Remove default redhat hardening"
          loop:
            - '01-permitrootlogin.conf'
            - '50-redhat.conf'
          notify: "Service restart sshd"
          ansible.builtin.file:
            path: "/etc/ssh/sshd_config.d/{{ item }}"
            state: absent

        - name: "SSH Configure hardened ciphers"
          notify: "Service restart sshd"
          ansible.builtin.copy:
            dest: /etc/ssh/sshd_config.d/90-rgm.conf
            src: openssh/90-rgm.conf
            owner: 'root'
            group: 'root'
            mode: '0600'
            seuser: 'system_u'
            serole: 'object_r'
            setype: 'etc_t'
            selevel: 's0'
