{
 "title": "4any k8s monitoring",
 "description": "Monitors Kubernetes cluster.",
 "tags": [
  "RGM",
  "Kubernetes",
  "4ANY"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_cpu_user_seconds_total, instance)"
   },
   {
    "name": "nodeexporter",
    "label": "Host:",
    "query": "label_values(node_memory_Active_bytes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{instance=~\"$node:.+\"}[$interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{instance=~\"$node:.+\"}[$interval]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"$node:.+\"}) / sum (machine_memory_bytes{instance=~\"$node:.+\"}) * 100"
      }
     ]
    },
    {
     "title": "Node CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"$node:.+\"}[1m])) / sum (machine_cpu_cores{instance=~\"$node:.+\"}) * 100"
      }
     ]
    },
    {
     "title": "Node filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$node:.+\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$node:.+\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"$node:.+\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{instance=~\"$node:.+\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"$node:.+\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{instance=~\"$node:.+\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$node:.+\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",instance=~\"$node:.+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name) * 100",
       "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}[$interval])) by (id, container_label_io_kubernetes_pod_name, name) * 100",
       "legendFormat": "pod: {{ container_label_io_kubernetes_pod_name }} | {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",instance=~\"$node:.+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
       "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}) by (id, container_label_io_kubernetes_pod_name, name)",
       "legendFormat": "pod: {{  container_label_io_kubernetes_pod_name }} | {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\",instance=~\"$node:.+\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
       "legendFormat": "-> {{ container_label_io_kubernetes_pod_namespace }} - {{ container_label_io_kubernetes_pod_name}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\",instance=~\"$node:.+\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
       "legendFormat": "<- {{ container_label_io_kubernetes_pod_namespace }} - {{ container_label_io_kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\",instance=~\"$node:.+\"}[$interval])) by (id, container_label_io_kubernetes_pod_name, name)",
       "legendFormat": "-> pod: {{ container_label_io_kubernetes_pod_name }} | {{ name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\",instance=~\"$node:.+\"}[$interval])) by (id, container_label_io_kubernetes_pod_name, name)",
       "legendFormat": "<- pod: {{ container_label_io_kubernetes_pod_name }} | {{ name }}"
      }
     ]
    }
   ]
  }
 ]
}