{
 "title": "Active Directory and DNS Dashboard",
 "description": "Active Directory and DNS Dashboard using Prometheus windows_Exporter",
 "tags": [
  "RGM",
  "windows",
  "ADDS",
  "DNS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "DNS Queries/Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(windows_dns_queries_total{protocol=\"udp\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections/Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches / Sec",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_searches_total{}[1m]))"
    }
   ]
  },
  { "title": "DNS Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "DNS Queries/Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_queries_total{}[1m])",
     "legendFormat": "in-{{protocol}} ({{instance}})"
    },
    {
     "expr": "-delta(windows_dns_responses_total{}[1m])",
     "legendFormat": "out-{{protocol}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Recursive Queries / Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_recursive_query_failures_total[1m])",
     "legendFormat": "failures ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_queries_total[1m])",
     "legendFormat": "queries ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_query_send_timeouts_total[1m])",
     "legendFormat": "sent timeouts ({{instance}})"
    }
   ]
  },
  { "title": "AD Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Pending Syncronisations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_synchronizations{})"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_operations{})"
    }
   ]
  },
  {
   "title": "Inbound Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_inbound_objects_updated_total{}[1m])",
     "legendFormat": "objects ({{instance}})"
    },
    {
     "expr": "delta(windows_ad_replication_inbound_properties_updated_total{}[1m])",
     "legendFormat": "properties ({{instance}})"
    }
   ]
  },
  {
   "title": "Intrasite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"outbound\"}[1m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Intersite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[1m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  { "title": "AD Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "AD Operations (Detailed)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_directory_operations_total{}[1m])",
     "legendFormat": "{{origin}}-{{operation}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Directory Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_database_operations_total{}[1m])",
     "legendFormat": "{{operation}} ({{instance}})"
    }
   ]
  },
  { "title": "AD Binds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "AD Bind",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_binds_total{}[1m])",
     "legendFormat": "{{bind_method}} ({{instance}})"
    }
   ]
  },
  { "title": "AD LDAP Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "LDAP Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m])",
     "legendFormat": "Opened ({{instance}})"
    },
    {
     "expr": "-(delta(windows_ad_ldap_closed_connections_total{}[1m]))",
     "legendFormat": "Closed ({{instance}})"
    }
   ]
  },
  { "title": "AD Heatmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "LDAP connections HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[1m])"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_searches_total{instance=\"ds-dc3:9182\"}[1m])"
    }
   ]
  },
  { "title": "AD LDAP Searches/Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "LDAP Searches/Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_ldap_writes_total{}[1m])",
     "legendFormat": "Writes ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_ldap_searches_total{}[1m])",
     "legendFormat": "Searches ({{instance}}"
    }
   ]
  },
  { "title": "DNS Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "DNS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_dns_memory_used_bytes_total{}[5m])",
     "legendFormat": "{{area}} ({{instance}})"
    }
   ]
  },
  { "title": "DNS Updates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_dynamic_updates_received_total[1m])",
     "legendFormat": "{{operation}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_dynamic_updates_failures_total[1m])",
     "legendFormat": "{{reason}} ({{instance}})"
    }
   ]
  }
 ]
}