{
 "title": "Multi-System metrics",
 "description": "Multi-System metrics from metricbeat to elasticsearch",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "elasticsearch" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.norm.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "event.module:system AND metricset.name:memory AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module:system AND metricset.name:filesystem AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "event.module:system AND metricset.name:memory AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.uptime.duration.ms",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total Disks Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 3 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.fsstat.total_size.used",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:fsstat AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "cpu",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "3",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "memory",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:memory AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "mount_point:{{term system.filesystem.mount_point}} - type:{{term system.filesystem.type}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.filesystem.mount_point",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "system.filesystem.type",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.filesystem.free",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:filesystem AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "mount_point:{{term system.filesystem.mount_point}} - type:{{term system.filesystem.type}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.filesystem.mount_point",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "system.filesystem.type",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:filesystem AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU cores utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.core.id",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.core.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:core AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "iowait",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "system",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.system.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "user",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.user.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:cpu AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Outbound Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "outbound:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Outbound Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.packets",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Inbound Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "inbound:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Inbound Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "outbound:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.packets",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Inbound Errors/Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.errors",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "Dropped:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.dropped",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Outbound Errors/Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.errors",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    },
    {
     "alias": "Dropped:{{term system.network.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.dropped",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "event.module:system AND metricset.name:network AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}