{
 "title": "Nutanix Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hypervisors IO Bandwith NTX-CLU-DCA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorIOBandwidth dagon.-value\", mean(\"warn\") AS \"hypervisorIOBandwidth dagon.-warn\", mean(\"warn-min\") AS \"hypervisorIOBandwidth dagon.-warn-min\", mean(\"warn-max\") AS \"hypervisorIOBandwidth dagon.-warn-max\", mean(\"crit\") AS \"hypervisorIOBandwidth dagon.-crit\", mean(\"crit-min\") AS \"hypervisorIOBandwidth dagon.-crit-min\", mean(\"crit-max\") AS \"hypervisorIOBandwidth dagon.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'DAGON' AND \"service\" = 'hypervisorIOBandwidth' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorIOBandwidth dagon.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hypervisors clusterLatency NTX-CLU-DCA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"clusterLatency NTX-CLU-DCA-value\", mean(\"warn\") AS \"clusterLatency NTX-CLU-DCA-warn\", mean(\"warn-min\") AS \"clusterLatency NTX-CLU-DCA-warn-min\", mean(\"warn-max\") AS \"clusterLatency NTX-CLU-DCA-warn-max\", mean(\"crit\") AS \"clusterLatency NTX-CLU-DCA-crit\", mean(\"crit-min\") AS \"clusterLatency NTX-CLU-DCA-crit-min\", mean(\"crit-max\") AS \"clusterLatency NTX-CLU-DCA-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'ARION' AND \"service\" = 'clusterLatency' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'clusterLatency NTX-CLU-DCA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DAGON utilisation CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")   AS \"hypervisorCpuUsagePercent dagon.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'DAGON' AND \"service\" = 'hypervisorCpuUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorCpuUsagePercent dagon.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ORBITAR utilisation CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")   AS \"hypervisorCpuUsagePercent orbitar.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'ORBITAR' AND \"service\" = 'hypervisorCpuUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorCpuUsagePercent orbitar.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARION utilisation CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\")   AS \"hypervisorCpuUsagePercent arion.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'ARION' AND \"service\" = 'hypervisorCpuUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorCpuUsagePercent arion.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DAGON hypervisorMemoryUsagePercent",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorMemoryUsagePercent dagon.-value\"  FROM \"metrics\" WHERE (\"host\" = 'DAGON' AND \"service\" = 'hypervisorMemoryUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorMemoryUsagePercent dagon.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ORBITAR hypervisorMemoryUsagePercent",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorMemoryUsagePercent orbitar.-value\"  FROM \"metrics\" WHERE (\"host\" = 'ORBITAR' AND \"service\" = 'hypervisorMemoryUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorMemoryUsagePercent orbitar.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ARION hypervisorMemoryUsagePercent",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorMemoryUsagePercent arion.-value\"  FROM \"metrics\" WHERE (\"host\" = 'ARION' AND \"service\" = 'hypervisorMemoryUsagePercent' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorMemoryUsagePercent arion.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "clusterUsedStorageCapacity  NTX-CLU-DCA",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"clusterUsedStorageCapacity NTX-CLU-DCA-value\", mean(\"warn\") AS \"clusterUsedStorageCapacity NTX-CLU-DCA-warn-max\", mean(\"crit\") FROM \"metrics\" WHERE (\"host\" = 'ARION' AND \"service\" = 'clusterUsedStorageCapacity' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'clusterUsedStorageCapacity NTX-CLU-DCA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "hypervisorWriteIOPerSecond ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorWriteIOPerSecond arion.-value\", mean(\"warn\") AS \"hypervisorWriteIOPerSecond arion.-warn\", mean(\"warn-min\") AS \"hypervisorWriteIOPerSecond arion.-warn-min\", mean(\"warn-max\") AS \"hypervisorWriteIOPerSecond arion.-warn-max\", mean(\"crit\") AS \"hypervisorWriteIOPerSecond arion.-crit\", mean(\"crit-min\") AS \"hypervisorWriteIOPerSecond arion.-crit-min\", mean(\"crit-max\") AS \"hypervisorWriteIOPerSecond arion.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'DAGON' AND \"service\" = 'hypervisorWriteIOPerSecond' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorWriteIOPerSecond arion.') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "hypervisorReadIOPerSecond ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"hypervisorWriteIOPerSecond arion.-value\", mean(\"warn\") AS \"hypervisorWriteIOPerSecond arion.-warn\", mean(\"warn-min\") AS \"hypervisorWriteIOPerSecond arion.-warn-min\", mean(\"warn-max\") AS \"hypervisorWriteIOPerSecond arion.-warn-max\", mean(\"crit\") AS \"hypervisorWriteIOPerSecond arion.-crit\", mean(\"crit-min\") AS \"hypervisorWriteIOPerSecond arion.-crit-min\", mean(\"crit-max\") AS \"hypervisorWriteIOPerSecond arion.-crit-max\" FROM \"metrics\" WHERE (\"host\" = 'DAGON' AND \"service\" = 'hypervisorWriteIOPerSecond' AND \"command\" = 'virt_ntx_snmp' AND \"performanceLabel\" = 'hypervisorWriteIOPerSecond arion.') AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}