{
 "title": "Realtime containers & nodes metrics",
 "description": "An overview of noticeable nodes and containers metrics.",
 "tags": [ "4any" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_cpu_user_seconds_total, instance)"
   },
   {
    "name": "nodeexporter",
    "label": "Host:",
    "query": "label_values(node_memory_Active_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "count(container_last_seen{instance=~\"$node:.+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"})",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "count(container_last_seen{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"})",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{instance=~\"$node:.+\",name=~\".+\"}[1m])) + sum(rate(container_cpu_system_seconds_total{id=\"/\",instance=~\"$node:.+\"}[1m])) + sum(rate(process_cpu_seconds_total{instance=~\"$node:.+|$nodeexporter:.+\"}[1m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Free and Used Disk Space on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"xfs\",instance=~\"$nodeexporter:.+\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "sum by (mountpoint) (node_filesystem_size_bytes{fstype=\"xfs\",instance=~\"$nodeexporter:.+\"} - node_filesystem_avail_bytes{fstype=\"xfs\",instance=~\"$nodeexporter:.+\"})",
     "legendFormat": "Used - {{instance}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Available Memory on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$nodeexporter:.+\"}",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$nodeexporter:.+\"} - node_memory_MemAvailable_bytes{instance=~\"$nodeexporter:.+\"}",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$nodeexporter:.+\"}[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$nodeexporter:.+\"}[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    },
    {}
   ]
  },
  {
   "title": "System Load on Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"^node_load.*\",instance=~\"$nodeexporter:.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network Traffic on Node",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$node:.+\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$node:.+\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod (Stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name) * 100",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Pod (Stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\",container_label_io_kubernetes_pod_namespace!~\"argo-dp|\"}[$interval])) by (container_label_io_kubernetes_pod_namespace, container_label_io_kubernetes_pod_name)",
     "legendFormat": "{{container_label_io_kubernetes_pod_namespace}} : {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    { "expr": "cadvisor_version_info", "legendFormat": "Host OS Version: {{osVersion}}" },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}