" Ansible Managed file - RGM installation

" disables Vi compatibility, so gets full Vim experience
set nocompatible
" do *not* expand tabs (eg. replacing tab escape char. by spaces)
set noexpandtab
" enable command completion in command mode
set wildmenu

set backspace=indent,eol,start
set tabstop=2
set shiftwidth=2

set autoindent
set smartindent
set nowrap
set expandtab
set paste

set bg=dark
set ru
set modeline

set nonumber
noremap <silent> <F2> :set number!<CR>

set pastetoggle=<F3>

" Caractères spéciaux
noremap <silent> <F4> :set list!<CR>

syntax on
